blank_issues_enabled: true
contact_links:
  - name: General Questions
    url: https://github.com/processhacker/processhacker/discussions/new
    about: Have a question? Start a new discussion.
  - name: Review open issues
    url: https://github.com/processhacker/processhacker/issues
    about: Check existing bug reports for already reported issues.
